apiVersion: v1
kind: Service
metadata:
  name: kamalapp-service
  namespace: default
  labels:
    app: kamalapp
spec:
  type: ClusterIP
  selector:
    app: kamalapp
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
